# Generated by Django 5.0.3 on 2024-03-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('ASSOCIATE', 'Associate')], default='Associate', max_length=15),
        ),
    ]
