# Generated by Django 5.0.3 on 2024-03-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_lead_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='team',
        ),
    ]
